name: SAST Scan
jobs:
  sast-scan:
    uses: splunk/sast-scanning/.github/workflows/sast-scan.yml@main
    secrets: inherit
on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]